
// bletooth scann service
export const DEVICE_STATE_DISCONNECT = 'DISCONNECT'
export const DEVICE_STATE_DISCONNECTING = 'DISCONNECTING'
export const DEVICE_STATE_DISCONNECTED = 'DISCONNECTED'
export const DEVICE_STATE_CONNECT = 'CONNECT'
export const DEVICE_STATE_CONNECTING = 'CONNECTING'
export const DEVICE_STATE_DISCOVERING = 'DISCOVERING'
export const DEVICE_STATE_FETCHING = 'FETCHING SERVICES AND CHARACTERISTICS'
export const DEVICE_STATE_CONNECTED = 'CONNECTED'
export const DEVICE_STATE_AUTH = 'DEVICE_STATE_AUTH'
export const DEVICE_STATE_SEARCH = 'DEVICE_STATE_SEARCH'
export const DEVICE_STATE_AUTH_REQUEST_NUMBER = 'DEVICE_STATE_AUTH_REQUEST_NUMBER'




export const START_SCAN = 'START_SCAN'
export const STOP_SCAN = 'STOP_SCAN'
export const DEVICE_FOUND = 'DEVICE_FOUND'
export const CHANGE_DEVICE_STATE = 'CHANGE_DEVICE_STATE'

export const WRITE_CHARACTERISTIC = 'WRITE_CHARACTERISTIC'
export const READ_CHARACTERISTIC = 'READ_CHARACTERISTIC'
export const MONITOR_CHARACTERISTIC = 'NOTIFY_CHARACTERISTIC'

export const PUSH_ERROR = 'PUSH_ERROR'
export const POP_ERROR = 'POP_ERROR'
export const EXECUTE_TRANSACTION = 'EXECUTE_TRANSACTION'
export const COMPLETE_TRANSACTION = 'COMPLETE_TRANSACTION'

export const HEART_RATE_MEASURE = 'HEART_RATE_MEASURE';
export const CHANGE_AUTH = 'CHANGE_AUTH';
export const INCREMENT_TRY_DISCONNECTED = 'INCREMENT_TRY_DISCONNECTED';

// HEART RATE SERVICE
export const SCANNER_DECIVES = 'SCANNER_DECIVES';
export const PARINING_DEVICE = 'PARINING_DEVICE';
export const HEART_RATE_DASHBOARD = 'HEART_RATE_DASHBOARD';


