
export const ON_CHANGE_CHEST_PAIN_TYPE = 'onChangeChestPainType';
export const ON_CHANGE_GENDER = 'onChangeGender';
export const ON_CHANGE_AGE = 'onChangeAge';
export const ON_CHANGE_RESTING_BLOOD_PRESSURE = 'ON_CHANGE_RESTING_BLOOD_PRESSURE';
export const ON_CHANGE_CHOLESTEROLE = 'ON_CHANGE_CHOLESTEROLE';
export const ON_CHANGE_FASTING_BLOOD_SUGAR = 'ON_CHANGE_FASTING_BLOOD_SUGAR';
export const ON_CHANGE_RESTING_ECG = 'ON_CHANGE_RESTING_ECG';
export const ON_CHANGE_MAXIMUM_HEARTRATE = 'ON_CHANGE_MAXIMUM_HEARTRATE';
export const ON_CHANGE_EXERCISE_INDUCED_ANGINA = 'ON_CHANGE_EXERCISE_INDUCED_ANGINA';
export const ON_CHANGE_OLD_PEAK = 'ON_CHANGE_OLD_PEAK';
export const ON_CHANGE_SLOP = 'ON_CHANGE_SLOP';
export const ON_CHANGE_THAL = 'ON_CHANGE_THAL';
export const ON_CHANGE_NUMBER_OF_VESSELS_COLORED = 'ON_CHANGE_NUMBER_OF_VESSELS_COLORED';


export const ON_PREDICTING = 'ON_PREDICTING';
export const RESET_PREDICT = 'RESET_PREDICT';
export const NEXT_STEP = 'NEXT_STEP';
export const PREV_STEP = 'PREV_STEP';


// bletooth scann service
export const DEVICE_STATE_DISCONNECT = 'DISCONNECT'
export const DEVICE_STATE_DISCONNECTING = 'DISCONNECTING'
export const DEVICE_STATE_DISCONNECTED = 'DISCONNECTED'
export const DEVICE_STATE_CONNECT = 'CONNECT'
export const DEVICE_STATE_CONNECTING = 'CONNECTING'
export const DEVICE_STATE_DISCOVERING = 'DISCOVERING'
export const DEVICE_STATE_FETCHING = 'FETCHING SERVICES AND CHARACTERISTICS'
export const DEVICE_STATE_CONNECTED = 'CONNECTED'
export const DEVICE_STATE_AUTH = 'DEVICE_STATE_AUTH'
export const DEVICE_STATE_SEARCH = 'DEVICE_STATE_SEARCH'
export const START_HEART_RATE_MONITORING = 'START_HEART_RATE_MONITORING'
export const START_HEART_MEASUREMENT_MANUAL = 'START_HEART_MEASUREMENT_MANUAL'




export const START_SCAN = 'START_SCAN'
export const STOP_SCAN = 'STOP_SCAN'
export const DEVICE_FOUND = 'DEVICE_FOUND'
export const CHANGE_DEVICE_STATE = 'CHANGE_DEVICE_STATE'

export const WRITE_CHARACTERISTIC = 'WRITE_CHARACTERISTIC'
export const READ_CHARACTERISTIC = 'READ_CHARACTERISTIC'
export const MONITOR_CHARACTERISTIC = 'NOTIFY_CHARACTERISTIC'

export const PUSH_ERROR = 'PUSH_ERROR'
export const POP_ERROR = 'POP_ERROR'
export const EXECUTE_TRANSACTION = 'EXECUTE_TRANSACTION'
export const COMPLETE_TRANSACTION = 'COMPLETE_TRANSACTION'

export const DEVICE_STATE_AUTH_SUCCES = 'DEVICE_STATE_AUTH_SUCCES';
export const CHANGE_AUTH = 'CHANGE_AUTH';
export const INCREMENT_TRY_DISCONNECTED = 'INCREMENT_TRY_DISCONNECTED';

// HEART RATE 
export const SCANNER_DECIVES = 'SCANNER_DECIVES';
export const PAIRING_DEVICE = 'PAIRING_DEVICE';
export const HEART_RATE_DASHBOARD = 'HEART_RATE_DASHBOARD';
export const CHANGE_SCENE = 'CHANGE_SCENE';
export const UPDATE_HEART_RATE = 'UPDATE_HEART_RATE';


