// Predict disease
export const ON_CHANGE_PROPS_PREDICT = 'ON_CHANGE_PROPS_PREDICT';
export const UPDATE_PREDICTED = 'UPDATE_PREDICTED';
export const START_PREDTINING = 'START_PREDTINING';
export const RESET_PREDICT = 'RESET_PREDICT';



// bletooth scann service
export const DEVICE_STATE_DISCONNECT = 'DISCONNECT'
export const DEVICE_STATE_DISCONNECTING = 'DISCONNECTING'
export const DEVICE_STATE_DISCONNECTED = 'DISCONNECTED'

export const DEVICE_STATE_CONNECTING = 'CONNECTING'
export const DEVICE_STATE_DISCOVERING = 'DISCOVERING'
export const DEVICE_STATE_CONNECTED = 'CONNECTED'

export const DEVICE_STATE_AUTH_STARTED = 'DEVICE_STATE_AUTH_STARTED';
export const DEVICE_STATE_AUTH_PRESS_MIBAND = 'DEVICE_STATE_AUTH_PRESS_MIBAND';
export const DEVICE_STATE_AUTH_SUCCEEDED = 'DEVICE_STATE_AUTH_SUCCEEDED';
export const DEVICE_STATE_AUTH_FAILED = 'DEVICE_STATE_AUTH_FAILED';


export const START_HEART_RATE_MEASURE = 'START_HEART_RATE_MEASURE';
export const STOP_HEART_RATE_MEASURE = 'STOP_HEART_RATE_MEASURE';

export const CHANGE_NEEDS_AUTH = 'CHANGE_NEEDS_AUTH';
export const START_SCAN = 'START_SCAN'
export const STOP_SCAN = 'STOP_SCAN'
export const DEVICE_FOUND = 'DEVICE_FOUND'


export const PUSH_ERROR = 'PUSH_ERROR'
export const POP_ERROR = 'POP_ERROR'

// heart rate
export const UPDATE_HEART_RATE = 'UPDATE_HEART_RATE';
export const UPDATE_DATA_CHART = 'UPDATE_DATA_CHART';
export const START_TASK_BACKGROUND = 'START_TASK_BACKGROUND';
export const STOP_TASK_BACKGROUND = 'STOP_TASK_BACKGROUND';
export const SEND_ALERT = 'SEND_ALERT';
export const ON_CHANGE_EMAIL = 'ON_CHANGE_EMAIL';

//user
export const USER_START_AUTHORIZING = 'USER_START_AUTHORIZING'
export const USER_AUTHORIZED = 'USER_AUTHORIZED'
export const USER_NO_EXIST = 'USER_NO_EXIST'
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
export const LOGOUT_SUCCES = 'LOGOUT_SUCCES'

//GLOBAL

export const RESET_STATE = 'RESET_STATE';







