
export const ON_CHANGE_CHEST_PAIN_TYPE = "onChangeChestPainType";
export const ON_CHANGE_GENDER = "onChangeGender";
export const ON_CHANGE_AGE = "onChangeAge";
export const ON_CHANGE_RESTING_BLOOD_PRESSURE = "ON_CHANGE_RESTING_BLOOD_PRESSURE";
export const ON_CHANGE_CHOLESTEROLE = "ON_CHANGE_CHOLESTEROLE";
export const ON_CHANGE_FASTING_BLOOD_SUGAR = "ON_CHANGE_FASTING_BLOOD_SUGAR";
export const ON_CHANGE_RESTING_ECG = "ON_CHANGE_RESTING_ECG";
export const ON_CHANGE_MAXIMUM_HEARTRATE = "ON_CHANGE_MAXIMUM_HEARTRATE";
export const ON_CHANGE_EXERCISE_INDUCED_ANGINA = "ON_CHANGE_EXERCISE_INDUCED_ANGINA";
export const ON_CHANGE_OLD_PEAK = "ON_CHANGE_OLD_PEAK";
export const ON_CHANGE_SLOP = "ON_CHANGE_SLOP";
export const ON_CHANGE_THAL = "ON_CHANGE_THAL";
export const ON_CHANGE_NUMBER_OF_VESSELS_COLORED = "ON_CHANGE_NUMBER_OF_VESSELS_COLORED";


export const ON_PREDICTING = "ON_PREDICTING";
export const RESET_PREDICT = "RESET_PREDICT";
export const NEXT_STEP = "NEXT_STEP";
export const PREV_STEP = "PREV_STEP";