export const STEP_START = 0;
export const STEP_2 = 4;
export const STEP_END = 4;


export const ON_CHANGE_CHEST_PAIN_TYPE = "onChangeChestPainType";
export const ON_CHANGE_GENDER = "onChangeGender";
export const ON_CHANGE_AGE = "onChangeAge";
export const ON_CHANGE_RESTING_BLOOD_PRESSURE = "ON_CHANGE_RESTING_BLOOD_PRESSURE";
export const ON_CHANGE_CHOLESTEROLE = "ON_CHANGE_CHOLESTEROLE";
export const ON_CHANGE_FASTING_BLOOD_SUGAR = "ON_CHANGE_FASTING_BLOOD_SUGAR";
export const ON_CHANGE_RESTING_ECG = "ON_CHANGE_RESTING_ECG";
export const ON_CHANGE_MAXIMUM_HEARTRATE = "ON_CHANGE_MAXIMUM_HEARTRATE";
export const ON_CHANGE_EXERCISE_INDUCED_ANGINA = "ON_CHANGE_EXERCISE_INDUCED_ANGINA";
export const ON_CHANGE_OLD_PEAK = "ON_CHANGE_OLD_PEAK";